[2023-09-19T12:30:29.282+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: udac_example_dag.Load_songplays_fact_table manual__2023-09-19T12:30:19.465263+00:00 [queued]>
[2023-09-19T12:30:29.299+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: udac_example_dag.Load_songplays_fact_table manual__2023-09-19T12:30:19.465263+00:00 [queued]>
[2023-09-19T12:30:29.299+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-19T12:30:29.333+0000] {taskinstance.py:1382} INFO - Executing <Task(LoadFactOperator): Load_songplays_fact_table> on 2023-09-19 12:30:19.465263+00:00
[2023-09-19T12:30:29.346+0000] {standard_task_runner.py:57} INFO - Started process 132 to run task
[2023-09-19T12:30:29.350+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'udac_example_dag', 'Load_songplays_fact_table', 'manual__2023-09-19T12:30:19.465263+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp5vil7lx8']
[2023-09-19T12:30:29.351+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask Load_songplays_fact_table
[2023-09-19T12:30:29.438+0000] {task_command.py:415} INFO - Running <TaskInstance: udac_example_dag.Load_songplays_fact_table manual__2023-09-19T12:30:19.465263+00:00 [running]> on host 8cbc6d342cd4
[2023-09-19T12:30:29.601+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kstine' AIRFLOW_CTX_DAG_ID='udac_example_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T12:30:19.465263+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T12:30:19.465263+00:00'
[2023-09-19T12:30:29.604+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/load_fact.py", line 27, in execute
    aws_credentials = self.__get_aws_credentials()
AttributeError: 'LoadFactOperator' object has no attribute '_LoadTableOperator__get_aws_credentials'
[2023-09-19T12:30:29.620+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Load_songplays_fact_table, execution_date=20230919T123019, start_date=20230919T123029, end_date=20230919T123029
[2023-09-19T12:30:29.651+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task Load_songplays_fact_table ('LoadFactOperator' object has no attribute '_LoadTableOperator__get_aws_credentials'; 132)
[2023-09-19T12:30:29.682+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T12:30:29.697+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
